account: nordnet_salkkuraportti
columns:
  amount: market_value
  date: date
  description: stock
  info: account
date_format: '%d.%m.%Y'
day_first: true
delimiter: ','
pattern: nordnet_salkkuraportti_preprocessed.csv
