account: penno
columns:
  amount: Summa
  date: "P\xE4iv\xE4m\xE4\xE4r\xE4"
  description: Kategoria
  info: Selite
date_format: '%Y-%m-%d %H:%M:%S.%f|%Y-%m-%d %H:%M:%S'
day_first: false
delimiter: ;
pattern: penno
