"id": "4"
"pattern": "tulot.csv"
"account": "tulot"
"delimiter": ","
"date_format": "%d.%m.%Y"
"day_first": "TRUE"
"columns":
  "date": "date"
  "amount": "amount"
  "description": "description"
  "info": "info"
